[en]
  title = "Kevin Liu's Nucleus"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

#[ko]
#  title = "Kevin Liu's Nucleus"
#  languageName = "한국어"
#  weight = 2
#  languagedir = "ltr"
#  contentdir = "content/ko"
